server:
  port: ${SERVER_PORT:8004}
  servlet:
    context-path: ${CONTEXT_PATH:/auth-api}

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui/index.html

spring:
  application:
    name: auth-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/auth_db}
    username: ${DB_USERNAME:bict}
    password: ${DB_PASSWORD:bict4486}

